### ISSUE TITLE
Wiimote: No devices found

### ISSUE THREAD

**Issue by vegarasmul** [G33kDude/pyev3#3]
Hey, thanks for making this nice lib! I have been playing with the Wiimote script, trying to get my EV3 to run. However, it seems like the Devices class needs an update.

I have my motors in Output A and D, so I've updated my script. However, no matter how I plug it, I get this:

```
Traceback (most recent call last):
  File "./wii-drive.py", line 36, in <module>
    left_motor = pyev3.Motor(pyev3.OUTPUT_D)
  File "/home/robot/WII/pyev3.py", line 102, in __init__
    LEGO_PORT_NAME=port or '*' #,
  File "/home/robot/WII/pyev3.py", line 21, in __init__
    raise IndexError('No devices found')
```

The 'devices' variable seems empty no matter what I do, so I guess the problem lies in whatever magic the pyudev line does.

Any help would be greatly appreciated by myself and my son. Thanks again!

**Comment by Jacob-Brink** [comment]
I am new to Github, so I don't know if I can go off topic, but what version of RCX are you using and have you gotten the basic functionality to work without the wiiremote?
